[package]
name = "cosmwasm-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmos-sdk-proto = "0.20.0"
prost = "0.12.1"
prost-types = "0.12.1"
tonic = "0.10.2"
